# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_submissions" do
  # This should return the minimal set of attributes required to create a valid
  # UserSubmission. As you add validations to UserSubmission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      UserSubmission.create! valid_attributes
      get user_submissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_submission = UserSubmission.create! valid_attributes
      get user_submission_url(user_submission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_submission_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserSubmission" do
        expect do
          post user_submissions_url, params: { user_submission: valid_attributes }
        end.to change(UserSubmission, :count).by(1)
      end

      it "redirects to the created user_submission" do
        post user_submissions_url, params: { user_submission: valid_attributes }
        expect(response).to redirect_to(user_submission_url(UserSubmission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserSubmission" do
        expect do
          post user_submissions_url, params: { user_submission: invalid_attributes }
        end.not_to change(UserSubmission, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_submissions_url, params: { user_submission: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end
end
