# frozen_string_literal: true

require "rails_helper"

RSpec.describe ConvertFile::InpToHash, type: :service do
  describe ".call" do
    context "when convert inp files to hash sucessful" do
      before { create(:object_type, :objects_type_list) }

      it "returns the number of arrays generated by the file" do
        user_submission = create(:user_submission)

        result = described_class.call(user_submission.files.first, user_submission)

        expect(result.size).to eq 765
      end

      it "returns an array of objects that contain some specific keys" do
        user_submission = create(:user_submission)

        result = described_class.call(user_submission.files.first, user_submission)

        expect(result.first).to include(:name, :object_type, :user_submission, :properties)
      end
    end
  end
end
